### ISSUE TITLE
出错了 

### ISSUE THREAD

**Issue by luke20223** [281677160/build-actions#100]
Collecting package info: done
Collecting target info: merging...
**Collecting target info: doneUpdating feed 'helloworld' from 'https://github.com/fw876/helloworld.git' ...**
Cloning into './feeds/helloworld'...
**Updating feed 'passwall3' from 'https://github.com/xiaorouji/openwrt-passwall.git;packages' ...**
Cloning into './feeds/passwall3'...
warning: Could not find remote branch packages to clone.
fatal: Remote branch packages not found in upstream origin
failed.
Collecting package info: feeds/helloworld/xray-plugin
Collecting package info: merging...
Collecting package info: done
Collecting target info: merging...
**Collecting target info: doneCreate index file './feeds/passwall3.index'** 
find: ‘feeds/passwall3’: No such file or directory

Collecting package info: merging...
**Collecting package info: donefind: ‘feeds/passwall3’: No such file or directory**

Collecting target info: merging...
Collecting target info: done
Error: Process completed with exit code 1.

仓库  注释掉

**Comment by 281677160** [comment]
已经修复了，passwall的仓库改链接了
