### ISSUE TITLE
package/feeds/passwall3/xray-plugin无法编译

### ISSUE THREAD

**Issue by authon** [281677160/build-actions#107]
make[3] -C feeds/passwall3/xray-plugin compile
    ERROR: package/feeds/passwall3/xray-plugin failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/Ledemaster/openwrt/include/toplevel.mk:231: world] Error 1
make[2]: Entering directory '/Ledemaster/openwrt/scripts/config'
make[2]: 'conf' is up to date.

**Comment by tom2025** [comment]
ERROR: package/feeds/passwall3/xray-core failed to build.

**Comment by 281677160** [comment]
golang版本引起的错误，现在应该没问题了，源码作者基本都更新了最新的golang版本
