### ISSUE TITLE
请问怎么取消默认quickstart插件的安装

### ISSUE THREAD

**Issue by ShmilyStar** [281677160/build-actions#112]

**Comment by 281677160** [comment]
你选了luci-app-istorex这个插件，它就自带的，你可以尝试在luci-app-istorex/Makefile里面用命令去掉+luci-app-quickstart看看，反正这个作者的插件一般都没啥用，人家都是写来给他自己的固件代码用的，我懒的去尝试了

**Comment by ShmilyStar** [comment]
流程指向的是你common仓库的common.sh，fork你的common和openwrt-package仓库后，怎么修改workflows文件指定到自己fork的仓库
