### ISSUE TITLE
大佬，请教下这个错误代码原因

### ISSUE THREAD

**Issue by ShmilyStar** [281677160/build-actions#115]
mkfs/rootdir.c: In function 'btrfs_mkfs_shrink_fs':
mkfs/rootdir.c:917:23: error: storage size of 'file_stat' isn't known
  917 |         struct stat64 file_stat;
      |                       ^~~~~~~~~
make[4]: *** [Makefile:414: mkfs/rootdir.o] Error 1
make[4]: Leaving directory '/Ledemaster/openwrt/build_dir/target-x86_64_musl/btrfs-progs-v5.16.1'
make[3]: *** [Makefile:100: /Ledemaster/openwrt/build_dir/target-x86_64_musl/btrfs-progs-v5.16.1/.built] Error 2
make[3]: Leaving directory '/Ledemaster/openwrt/feeds/packages/utils/btrfs-progs'
time: package/feeds/packages/btrfs-progs/compile#0.23#0.06#0.26
    ERROR: package/feeds/packages/btrfs-progs failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/btrfs-progs/compile] Error 1
make[2]: Leaving directory '/Ledemaster/openwrt'
make[1]: *** [package/Makefile:110: /Ledemaster/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/Ledemaster/openwrt'
make: *** [/Ledemaster/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

**Comment by 281677160** [comment]
可能是btrfs-progs版本过低吧，换了一个高版本的了，你自己去编译测试看看吧
