### ISSUE TITLE
成功编译，但刷机后进不去系统

### ISSUE THREAD

**Issue by tom2025** [281677160/build-actions#116]
大家可以测试，固件地址：
https://pipelinesghubeus15.actions.githubusercontent.com/MCOAQCx8yrYofj1ck2xj94ayr9ottIFPhTQIfmG6zkGtXffQXj/_apis/pipelines/1/runs/4/signedartifactscontent?artifactName=Lede-18.06-x86-64-firmware-2024-0115-1906&urlExpires=2024-01-16T10%3A32%3A42.2072178Z&urlSigningMethod=HMACV2&urlSignature=GbyvAqezRZwj4AagEJ4WO%2BgEQLy%2FXMOUUA5c1RfML24%3D

**Comment by 281677160** [comment]
![QQ截图20240116212451](https://github.com/281677160/build-actions/assets/66651997/ca0c0d39-312c-484b-97e0-26fa331d263a)
