### ISSUE TITLE
luci-app-argon-config每次都会自动编译进去，如何强制取消？

### ISSUE THREAD

**Issue by drw2005** [281677160/build-actions#119]
编译时明明没有选择，但是出来的固件里都有luci-app-argon-config，请教大佬如何取消不编译进固件哩？
谢谢！

**Comment by drw2005** [comment]
> x86的你选择luci-app-argon主题就自带的

有没有办法强制不安装它

**Comment by tom2025** [comment]
修改默认主题就可以取消
# 默认主题设置
export Mandatory_theme="ifit"               
export Default_theme="itit"

**Comment by 281677160** [comment]
> > x86的你选择luci-app-argon主题就自带的
> 
> 有没有办法强制不安装它

现在开始在配置文件去掉它后，应该就不会自带了
