### ISSUE TITLE
关于在线更新

### ISSUE THREAD

**Issue by authon** [281677160/build-actions#123]
不知道为啥两天编译的新固件，更新后需要重新设置密码。之前在线更新没有这个问题。(diy里面一直都是设置的无密码)

diy里OpenClash内核选择的“2”(Meta三核那个)，在线更新后进去openclash还需要重新在版本更新那里点一下meta的版本更新，openclash才能启动。

**Comment by 281677160** [comment]
将就用吧，我看了下，密码文件是保留的，但是不知道为什么不会保留原来的密码，还有就是openclash的那个内核也保留的，但是检测不到，可能是插件的问题吧
