### ISSUE TITLE
求教两个问题

### ISSUE THREAD

**Issue by xlfq3136** [281677160/build-actions#124]
1、编译的office 23.05源码，路由型号是极路由HIWIFI HC5962，成功安装后提示无线未关联已禁用，可以修改wifi名和密码但一直启用不了没有wlan怎么回事？源码编译的时候对照着lienol勾选kmod了啊？
2、求教diy里自定义增加ipk软件源码的代码，试了git和srt git一直失败。或者大大增加下aliyun-webdav的源码，这个我经常用，谢谢。

**Comment by tom2025** [comment]
有个无线工具wireless tool要勾选上，好像在base菜单里

**Comment by xlfq3136** [comment]
wireless tool我对照着Lienol的源码都选上了，还是不管用。再求教个问题，Padavan哪个大大的源码还在更新可以自编译用，原生中继支持IPV6吗？

**Comment by 281677160** [comment]
无线问题不了解，没用过无线的，office源码已经加入aliyun-webdav，自己测试一下能不能用吧
