### ISSUE TITLE
提交一个算bug吗？

### ISSUE THREAD

**Issue by xlfq3136** [281677160/build-actions#125]
通过make menuconfig对插件进行自定义选择后，即使全部取消编译ssr相关内容项，在生成config的时候还是会有一项内容被自动生成，我的表现为第41行：
41	CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks_NONE_Client=y
不知道这个会不会编译相关内容，正常格式应该是#……is not set 
后来又看了下，是把ssr的一项内容设置成none选项的时候会出现这种情况。

**Comment by 281677160** [comment]
呃，config配置文件一直都是这样啊，生成的附带文件不一定会全部取消的，特别是有一些插件导致编译错误的，你去取消了，其实它还有某文件滞留在config文件里面，导致一直都会编译错误，配置文件用久了就要时不时的清理一下，就是保留最前面的三行机型文件，重新选择插件
