### ISSUE TITLE
编译后DHCP/DNS选项报错是怎么回事？

### ISSUE THREAD

**Issue by xlfq3136** [281677160/build-actions#127]
原先编译Lienol的固件使用了AdguardHome插件，后来再编译就去掉了，每次刷机都是先重置刷固件后再重置，最近编译的固件没有AdguardHome插件了吗？还有就是接口选项下的DHCP/DNS报错（命令如下），倒是不影响使用：
ReferenceError
Associated tab not declared
at ClassConstructor.taboption (http://192.168.1.1/luci-static/resources/form.js?v=22.03:74:9)
at ClassConstructor.render (http://192.168.1.1/luci-static/resources/view/network/dhcp.js?v=22.03:55:1056)
有解决办法吗？

**Comment by zow2023** [comment]
我也遇见一样的问题 请问解决没？

**Comment by xlfq3136** [comment]
> 我也遇见一样的问题 请问解决没？

换一个源码版本重新编译就好了。我换了23.05的

**Comment by zow2023** [comment]
我用的是lienol 22.03的，软件包用了kenzok8的。不想换源码的情况下有啥解决办法没。我是小白，。

**Comment by xlfq3136** [comment]
那我就不知道了。提供个思路你可以试一下，先刷成padavan再刷回lienol。

**Comment by zow2023** [comment]
感谢你的回复  我的机器是E8450
