### ISSUE TITLE
编译immortalwrt时，选择版本23.05，会自动选snapshot，怎么指定23.05.1呢？

### ISSUE THREAD

**Issue by qr4d** [281677160/build-actions#134]
snapshot的内核版本是5.14.148，很多插件装不上，而23.05.1的内核版本是5.14.147，可以安装

怎么在编译的时候，指定23.05为23.05.1呢？

**Comment by xlfq3136** [comment]
求教immortalwrt比openwrt好用吗？immortalwrt用不用自己选择wifi驱动啥的，还是make menuconfig的时候指定型号就可以了？

**Comment by 281677160** [comment]
> snapshot的内核版本是5.14.148，很多插件装不上，而23.05.1的内核版本是5.14.147，可以安装
> 
> 怎么在编译的时候，指定23.05为23.05.1呢？

等天气没那么冷了，我又比较闲的时候再跟你说这个问题，现在天气又冷，我又累，不想动

**Comment by 281677160** [comment]
> snapshot的内核版本是5.14.148，很多插件装不上，而23.05.1的内核版本是5.14.147，可以安装
> 
> 怎么在编译的时候，指定23.05为23.05.1呢？

不是一直都用着23.05.1？
![QQ截图20240304001015](https://github.com/281677160/build-actions/assets/66651997/927b5a6f-ef1d-4fb3-8810-d231988ef5d3)
