### ISSUE TITLE
Immortalwrt 固件编译出问题了 虽然能编译成功,但是网络不通

### ISSUE THREAD

**Issue by zh15933** [281677160/build-actions#140]
Immortalwrt 固件编译出问题了 虽然能编译成功,但是网络不通,作者可不可以试一试?我是用在PVE虚拟机上的,LEDE固件倒是正常

**Comment by zh15933** [comment]
当旁路由用的
![1](https://github.com/281677160/build-actions/assets/32957590/2b4f2447-fa03-4784-b1d9-c9e4e0ff9674)
![2](https://github.com/281677160/build-actions/assets/32957590/54d9f0a1-2437-4da8-a8c4-10fd6314f095)
![3](https://github.com/281677160/build-actions/assets/32957590/adaf8f97-7e1f-4a97-ae99-7b2ade49e905)

**Comment by 281677160** [comment]
DNS问题
![QQ截图20240302225606](https://github.com/281677160/build-actions/assets/66651997/976897d6-881b-4303-861e-b693272ffef0)

**Comment by zh15933** [comment]
> DNS问题 ![QQ截图20240302225606](https://private-user-images.githubusercontent.com/66651997/309480923-976897d6-881b-4303-861e-b693272ffef0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzOTE3OTIsIm5iZiI6MTcwOTM5MTQ5MiwicGF0aCI6Ii82NjY1MTk5Ny8zMDk0ODA5MjMtOTc2ODk3ZDYtODgxYi00MzAzLTg2MWUtYjY5MzI3MmZmZWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDE0NTgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMjIyYjlkYmM5ZmY5YzhjOTdkYjBlNjQxMTgyMjI5NWU0MTA4NjMxMzA3YzBmZWY1NTFiZTIwY2RhOTdiMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tCamPLzfI7MYeOuYjW55YtfyNnH4pRJs5aLLqxg7F1E)

好的 谢谢指导  我去试一试
