### ISSUE TITLE
希望passwall插件 里的 ChinaDNS-NG 每次编译都升级到新版本

### ISSUE THREAD

**Issue by zh15933** [281677160/build-actions#163]
不用每次固件升级后,还需要手动升级ChinaDNS-NG 版本 才能让passwall正常使用

![Snipaste_2024-08-19_23-54-16](https://github.com/user-attachments/assets/dc6a46e8-901d-4c53-87e9-57006079a017)

**Comment by 281677160** [comment]
已经解决了
