### ISSUE TITLE
编译efi固件的时候   发现不能单独编译出efi固件

### ISSUE THREAD

**Issue by zh15933** [281677160/build-actions#166]
选择只编译efi固件时
即使在源码中不勾选legacy,编译完成时也会有legacy固件
![Snipaste_2024-08-23_21-35-07](https://github.com/user-attachments/assets/a5c4e1a9-ed0d-4f28-8c00-c485051603f2)
![Snipaste_2024-08-23_22-35-07](https://github.com/user-attachments/assets/e6f93605-59bd-4bd5-b3db-2ed8da3d1e12)

但是只编译legacy固件的时候 ,就正常了,不会有efi固件

**Comment by 281677160** [comment]
这个是特意的，因为好多设备efi的固件是不能在线更新的，特别是用虚拟机安装的openwrt，基本都不能用efi，要保留legacy格式在成行，就算多了legacy这个没影响的啥的
