### ISSUE TITLE
'udp2raw-tunnel', which does not exist

### ISSUE THREAD

**Issue by klmmlk** [281677160/build-actions#31]
老哥，这几次编译都失败了，我没有选择luci-app-udp2raw也会报如下的错误，不知道怎么解决。麻烦了。
WARNING: Makefile 'package/feeds/luci/luci-app-udp2raw/Makefile' has a dependency on 'udp2raw-tunnel', which does not exist

**Comment by 281677160** [comment]
没选择luci-app-udp2raw编译失败，自己看日志，luci-app-udp2raw报错也修复好了

**Comment by klmmlk** [comment]
谢谢大佬。
