### ISSUE TITLE
大神，请问怎么在云编译时间加入vmdk格式

### ISSUE THREAD

**Issue by 18690819111** [281677160/build-actions#32]
你好，我想编译时间加入vmdk格式的固件，问一下需要改哪个脚本。
本人小白，全靠大神的教程一步一步编译的。
勿笑，老年人，没办法

**Comment by 281677160** [comment]
https://github.com/danshui-git/shuoming/blob/master/overlay.md

**Comment by 18690819111** [comment]
谢谢
