### ISSUE TITLE
fatal: could not read Username for 'https://github.com': No such device or address

### ISSUE THREAD

**Issue by Samueli924** [281677160/build-actions#35]
你好 我在Action触发compile启动编译的时候出现了这个错误  
![Snipaste_2021-12-14_14-55-35](https://user-images.githubusercontent.com/65054820/145948304-8408eed1-16d4-4638-985f-8feda46afdf9.png)
出错问题来自于  
![Snipaste_2021-12-14_14-56-15](https://user-images.githubusercontent.com/65054820/145948364-11079a48-eebe-450d-8cec-db6aeb52cb78.png)

------

我Secrets里的REPO_TOKEN配置好了  

重新跑了两次也出现同样的错误  

请问怎么解决，谢谢

**Comment by 281677160** [comment]
你的是私库是吧？

**Comment by Samueli924** [comment]
噢，是这个问题啊！我再试试

**Comment by Samueli924** [comment]
可以正常运行了 谢谢！建议这里加个判断啥的免得后面又有人提Issue
