### ISSUE TITLE
请教一个问题：

### ISSUE THREAD

**Issue by Tao173** [281677160/build-actions#45]
编译的时候删除默认密码该怎么写？我试了几个都不行，L大的源码。（一个web的密码password，另一个putty那个web页面的密码）
麻烦指点一下，多谢。

[https://github.com/Tao173/Actions-OpenWrt-Node/blob/main/diy-part2.sh](url)

**Comment by 281677160** [comment]
![QQ截图20220401180429](https://user-images.githubusercontent.com/66651997/161242565-3fa9e432-5ca8-4c6e-8a04-daaed58b8f6f.png)

**Comment by Tao173** [comment]
我是用的P3TERX的原仓库模板，diy2.sh直接用uci会报错，我试过sed -i 's/\/bin\/login/\/bin\/login -f root/' /etc/init.d/ttyd 
但是好像也不行，有其他办法吗。。。

**Comment by Tao173** [comment]
使用P3TERX的原仓库模板要修改sed -i '/CYXluq4wUazHjmCDBCqXF/d' package/lean/default-settings/files/zzz-default-settings特来说明一下。。感谢本仓库大佬的指点 @281677160
