### ISSUE TITLE
使用lede源码，启动openwrt时不显示代码是否跑完，直接黑屏 

### ISSUE THREAD

**Issue by jiawm** [281677160/build-actions#48]
如题，使用lede源码，启动openwrt时不显示代码是否跑完，直接黑屏，请问老大如何解决，谢谢

**Comment by 281677160** [comment]
这个问题，不好解决，我完全不知道什么情况，我还没练成仙

**Comment by jiawm** [comment]
> 这个问题，不好解决，我完全不知道什么情况，我还没练成仙

有没有可能是注入“openwrt”命令所致？

**Comment by 281677160** [comment]
应该是吧，反正就按您提供的条件，你说啥都能成立
