### ISSUE TITLE
lienol源码编译错误

### ISSUE THREAD

**Issue by jiawm** [281677160/build-actions#49]
请老大查看以下，编译无法成功
make[2]: *** [package/Makefile:70: package/install] Error 255
make[1]: *** [package/Makefile:111: /Lienol_source/openwrt/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make: *** [/Lienol_source/openwrt/include/toplevel.mk:230: world] Error 2

**Comment by 281677160** [comment]
就那么点日志，叫神仙才能看出来

**Comment by jiawm** [comment]
好了
