### ISSUE TITLE
opentomcat主题瑕疵

### ISSUE THREAD

**Issue by jiawm** [281677160/build-actions#51]
如图“商店”没有对齐
![屏幕截图 2022-04-18 204943](https://user-images.githubusercontent.com/42288069/163812582-a0b89e67-c928-48ba-970c-b3642c25d3f4.png)

**Comment by 281677160** [comment]
用argon主题就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/build-actions"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月18日(星期一) 晚上9:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[281677160/build-actions] opentomcat主题瑕疵 (Issue #51)





 
如图“商店”没有对齐

**Comment by jiawm** [comment]
无解，就关闭了
