### ISSUE TITLE
lienol源码编译luci-app-argon-config不可用

### ISSUE THREAD

**Issue by jiawm** [281677160/build-actions#52]
如题，lienol编译argon-config成功后不能使用。有没有可能是使用Lede 18.08LUCI。
...ib/lua/luci/model/cbi/argon-config/configuration.lua:3: module 'luci.model.ipkg' not found:
	no field package.preload['luci.model.ipkg']
	no file './luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg/init.lua'
	no file '/usr/lib/lua/luci/model/ipkg.lua'
	no file '/usr/lib/lua/luci/model/ipkg/init.lua'
	no file './luci/model/ipkg.so'
	no file '/usr/lib/lua/luci/model/ipkg.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	...ib/lua/luci/model/cbi/argon-config/configuration.lua:3: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1526: in function '_form'
	/usr/lib/lua/luci/dispatcher.lua:1054: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>

**Comment by 281677160** [comment]
22.03跟21.02的没修复这个东西，只需要用argon就行了，主题是适配了

**Comment by jiawm** [comment]
了解，谢谢
