### ISSUE TITLE
今天更新了源码后发现不能自动触发编译

### ISSUE THREAD

**Issue by jiawm** [281677160/build-actions#53]
![Screenshot_2022-04-20-22-21-42-536_mark via](https://user-images.githubusercontent.com/42288069/164252997-e42a88ee-a9a1-4fce-b7b2-f7e310e348a1.jpg)

**Comment by 281677160** [comment]
你的是私库是吧？

**Comment by 281677160** [comment]
私库就不用触发了啊，配置文件自己搞定，直接启动主文件就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/build-actions"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月20日(星期三) 晚上10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [281677160/build-actions] 今天更新了源码后发现不能自动触发编译 (Issue #53)





 
是私库，有解不

**Comment by jiawm** [comment]
好的，谢老大，明天再fork个public
