### ISSUE TITLE
云编译出现错误

### ISSUE THREAD

**Issue by wqzxhpx1988** [281677160/build-actions#54]
![07F7C442-C7E3-424F-9E9C-B578484DBA2D](https://user-images.githubusercontent.com/85534312/164373204-7b5fdd66-5223-4bd5-9705-0f2681c119f0.png)

**Comment by 281677160** [comment]
同步最新仓库再试试

**Comment by wqzxhpx1988** [comment]
昨天完全同步的最新仓库，从昨天开始一直出现这个错误好像是容量不够
![Uploading 8FB13BB3-4F29-4DEF-8A95-02FF490C0AA1.png…]()

**Comment by 281677160** [comment]
今天早上改了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/build-actions"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月21日(星期四) 中午12:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [281677160/build-actions] 云编译出现错误 (Issue #54)





 
昨天完全同步的最新仓库，从昨天开始一直出现这个错误好像是容量不够

**Comment by wqzxhpx1988** [comment]
![11E38862-BE1F-4D65-9408-8DCF1C0AFE09](https://user-images.githubusercontent.com/85534312/164374994-3a1fc1fd-d737-4346-9244-4f76fd4c0565.png)

**Comment by wqzxhpx1988** [comment]
我重新再同步试试

**Comment by 281677160** [comment]
同步完测试吧，同步后应该没问题了，昨天跟今天早上修改了几个BUG,我懒的去写公告了

**Comment by wqzxhpx1988** [comment]
好的大神，我同步后再试试，谢谢

**Comment by 281677160** [comment]
以前每次启动都同步compile.yml文件的时候省心多了，没修改diy-part.sh文件基本每次都是最新仓库

**Comment by wqzxhpx1988** [comment]
确实以前太省心了，现在还在编译，一会看看结果

**Comment by 281677160** [comment]
没办法，众口难调，有些人喜欢自己修改一下yml文件，显示些个性，刚修改了源码获取方式了，我都放common文件了，及时更新仓库

**Comment by wqzxhpx1988** [comment]
好的 ，固件稳定比什么都强，等一会编译完看下后再更新仓库

**Comment by wqzxhpx1988** [comment]
已经编译成功了，非常感谢
