### ISSUE TITLE
拉取了最新代码，又编译失败了

### ISSUE THREAD

**Issue by wqzxhpx1988** [281677160/build-actions#57]
您好，今天拉取最新代码，又云编译失败了，谢谢

**Comment by wqzxhpx1988** [comment]
![捕获](https://user-images.githubusercontent.com/85534312/172985241-800f0459-d330-4daf-892c-e7c36447df4e.PNG)

**Comment by Myoko** [comment]
取消 sagernet-core 编译就正常了！ 这个和 v2ray xray 有冲突

**Comment by wqzxhpx1988** [comment]
请问，这个在哪取消，谢谢大神

**Comment by wqzxhpx1988** [comment]
请问，这个在哪取消，谢谢大神

**Comment by wqzxhpx1988** [comment]
> 取消 sagernet-core 编译就正常了！ 这个和 v2ray xray 有冲突

请问大神，这个在哪取消 谢谢

**Comment by Myoko** [comment]
触发compile启动编译  手动编辑 luci app 里面的配置 然后下载config配置文件里面粘贴到你要编译的对应仓库的config

**Comment by wqzxhpx1988** [comment]
> 触发compile启动编译 手动编辑 luci app 里面的配置
> https://github.com/danshui-git/shuoming/blob/master/yijianconfig.md

我试一下提取出config文件后粘贴到lede那个文件夹的.config里，再运行compie吗

**Comment by wqzxhpx1988** [comment]
> 

![捕获](https://user-images.githubusercontent.com/85534312/173009106-b603e8d1-c2f9-44f5-90a7-7e250a092ca4.PNG)
真的是这个错误

**Comment by wqzxhpx1988** [comment]
> > 触发compile启动编译 手动编辑 luci app 里面的配置
> > https://github.com/danshui-git/shuoming/blob/master/yijianconfig.md
> 
> 我试一下提取出config文件后粘贴到lede那个文件夹的.config里，再运行compie吗
按照您的方法还是不行，应该是ssr+跟其他出国软件不能一起编译了
