### ISSUE TITLE
最近一段时间的自动更新固件失效了

### ISSUE THREAD

**Issue by cyj265** [281677160/build-actions#58]
![QQ截图20220611141323](https://user-images.githubusercontent.com/63035285/173176021-8d162f67-a1e0-40da-b07a-ce8af09628e5.png)
![R6T%L6) UFOH)NLB%H6_E$6](https://user-images.githubusercontent.com/63035285/173176023-5a859177-8029-4cfe-93be-3c99dd5aeb25.png)

**Comment by lqqk7** [comment]
x86固件刚刚我也遇到同样的问题了，自动更新也是一样的提示，找不到/mnt/back.tar.gz文件，同时后台luci界面也打不开了，看了一下/etc/config/luci文件也丢失
