### ISSUE TITLE
这错误怎么改

### ISSUE THREAD

**Issue by starxu1971** [281677160/build-actions#61]
lean源码是否包含mosdns的package，如果有，请删除并替换这边的版本，
https://github.com/coolsnowwolf/packages/tree/master/net/mosdns
和你库里的有冲突，现在要删除lean库里带的mosdns只用你库里的该怎么弄。

**Comment by 281677160** [comment]
加群去找解决办法吧，或者加群后找群里的大神修改后的仓库用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月4日(周一) 上午10:13
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [281677160/build-actions] 这错误怎么改 (Issue #61)




 
lean源码是否包含mosdns的package，如果有，请删除并替换这边的版本，
 https://github.com/coolsnowwolf/packages/tree/master/net/mosdns
 和你库里的有冲突，现在要删除lean库里带的mosdns只用你库里的该怎么弄。

**Comment by 281677160** [comment]
解决了，我直接删除了我插件包的这个插件，用大雕的吧

**Comment by starxu1971** [comment]
> 解决了，我直接删除了我插件包的这个插件，用大雕的吧

谢谢
