### ISSUE TITLE
大神，新的固件在编译store的过程中会提示缺少依赖，导致编译不成功，不知道是否如何补全

### ISSUE THREAD

**Issue by xiaofanxinxiang1** [281677160/build-actions#64]
大神，新的固件在编译store的过程中会提示缺少依赖，导致编译不成功，不知道是否如何补全
![4@{CDZ(ZO18(@Z6V{V0$LWX](https://user-images.githubusercontent.com/71212595/180682447-92734f87-c9b5-4368-a38d-1cef449092a7.png)

**Comment by 281677160** [comment]
应该搞好了，你去测试看看吧
