### ISSUE TITLE
想添加自己修改后的主题，但是会和原本feed里面的主题重名，要怎么操作？

### ISSUE THREAD

**Issue by eightsheep67** [281677160/build-actions#66]
大佬想请教一下，如果想添加自己修改后的主题，但是会和原本feed里面的主题重名，要怎么操作？
把原来neobird里跳转ssr的链接和图标都改成openclash了。
https://github.com/eightsheep67/luci-theme-neobird.git

还有我还发现，我最新编译的这一次，我勾选了neobird和rosy主题，也编译进去了软件包里看得到，但是在固件系统主题选项里没有，我只好删了手动安装ipk，才显示出来。这个是我哪里设置错了吗？

**Comment by 281677160** [comment]
要改什么就用files大法就可以了
