### ISSUE TITLE
Oscam编译出问题

### ISSUE THREAD

**Issue by yaak63** [281677160/build-actions#68]
最近一周三次编译，均在Oscam上出问题而失败，从前不曾遇到过。日志如下：请问是哪里可能有问题？
ERROR: package/feeds/danshui/openwrt_oscam failed to build. 
..................................................................................................................................................
void add_emu_reader(void);
       ^~~~~~~~~~~~~~
.c:52:7: warning: redundant redeclaration of 'stop_stream_server' [-Wredundant-decls]
  void stop_stream_server(void);
       ^~~~~oscam~~~~~~~~~~~~~
oscam.c:47:7: note: previous declaration of 'stop_stream_server' was here
  void stop_stream_server(void);
       ^~~~~~~~~~~~~~~~~~
oscam.c: In function 'write_versionfile':
oscam.c:388:34: warning: format '%ld' expects argument of type 'long int', but argument 3 has type 'time_t' {aka 'long long int'} [-Wformat=]
   fprintf(fp, "Unix starttime: %ld\n", walltime);
                                ~~^     ~~~~~~~~
                                %lld
.........................................................................................................................................................
...........................................................................................................................................................
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:446: Distribution/oscam.debug] Error 1
make[4]: *** [Makefile:418: all] Error 2
make[3]: *** [Makefile:156: /Lede_source/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/oscam-r11704_c5b2e65/.built] Error 2
make[4]: Leaving directory '/Lede_source/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/oscam-r11704_c5b2e65'
make[3]: Leaving directory '/Lede_source/openwrt/feeds/danshui/openwrt_oscam'
time: package/feeds/danshui/openwrt_oscam/compile#49.65#3.75#49.04
    ERROR: package/feeds/danshui/openwrt_oscam failed to build.
make[2]: *** [package/Makefile:116: package/feeds/danshui/openwrt_oscam/compile] Error 1
make[2]: Leaving directory '/Lede_source/openwrt'
make[1]: *** [package/Makefile:110: /Lede_source/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/Lede_source/openwrt'
make: *** [/Lede_source/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

**Comment by 281677160** [comment]
这个大概是gcc的问题吧，不知道怎么解决，本地编译我试过没问题，云编译怎么弄都弄不好
