### ISSUE TITLE
请教一个小问题

### ISSUE THREAD

**Issue by yongyesun** [281677160/build-actions#7]
现在想连接SSH进去配置固件就会停止编译，但停止编译后也会有一份配置文件，请问怎么能下载到这配置文件呢？

**Comment by 281677160** [comment]
https://github.com/danshui-git/shuoming/blob/master/4%E5%9B%BA%E4%BB%B6%E4%B8%8B%E8%BD%BD.md

**Comment by yongyesun** [comment]
谢谢回复，我开始以为是ssh连入的时候下载~~
