### ISSUE TITLE
出错了

### ISSUE THREAD

**Issue by starxu1971** [281677160/build-actions#70]
Run export matrixtarget="Lede_source"
Cloning into '/home/runner/work/build-actions/build-actions/build/common'...
  没有发现该源码，源码获取方法已更改，请及时同步仓库使用 
Error: Process completed with exit code 1.

**Comment by starxu1971** [comment]
Run export matrixtarget="Lede_source"
Cloning into '/home/runner/work/build-actions/build-actions/build/common'...
  没有发现该源码，源码获取方法已更改，请及时同步仓库使用 
Error: Process completed with exit code 1.

**Comment by 281677160** [comment]
请及时同步仓库，或者重新拉取仓库
