### ISSUE TITLE
新项目编译报错

### ISSUE THREAD

**Issue by gxnas** [281677160/build-actions#84]
刚才Fork的项目，编译到触发compile.yml启动“Lede”编译这个步骤就报错，已按照教程添加了REPO_TOKEN，报错信息如下：
Run cd ${GITHUB_WORKSPACE}
Cloning into 'Lede'...
CPU_PASSWORD\=\"1680575[77](https://github.com/gxnas/OpenWrt-Build-Actions/actions/runs/4603377770/jobs/8133330292#step:17:78)7\"
[main 7b070ec] 选择8370-编译-Lede-18.06-x86-64固件
 4 files changed, 50 insertions(+), 7 deletions(-)
 create mode 100755 build/Lede/relevance/16[80](https://github.com/gxnas/OpenWrt-Build-Actions/actions/runs/4603377770/jobs/8133330292#step:17:81)575777.ini
fatal: could not read Password for 'https://***@github.com': No such device or address
Error: Process completed with exit code 128.

**Comment by 281677160** [comment]
fatal: could not read Password for 'https://***@github.com': No such device or address
这里就写了啊
检测密匙
