### ISSUE TITLE
天靈固件進行到下載軟件就不行了，一直下載到 6 小時滿還在下

### ISSUE THREAD

**Issue by starxu1971** [281677160/build-actions#86]
反復測試只要修改了config文件就不停的的下載了，默認配置可以正常編譯。但是同樣配置的大雕就可以正常編譯。

**Comment by starxu1971** [comment]
官方版本編譯也一樣，SSH修改cofig后就不停下載了。

**Comment by 281677160** [comment]
不好意思，我没办法解决问题，你问了个寂寞，我看了个寂寞而已
没有日志，我去你仓库看，也是看了个寂寞，错误编译我也没看到
只会浪费彼此时间，我也不是天天那么有时间的
还有这个错误，应该就是某一个插件下载不了导致的，你有时间，可以一个个的排除，哪个插件有问题，你不编译就可以了

**Comment by starxu1971** [comment]
> 不好意思，我没办法解决问题，你问了个寂寞，我看了个寂寞而已 没有日志，我去你仓库看，也是看了个寂寞，错误编译我也没看到 只会浪费彼此时间，我也不是天天那么有时间的 还有这个错误，应该就是某一个插件下载不了导致的，你有时间，可以一个个的排除，哪个插件有问题，你不编译就可以了

你可以現在去看下大雕的在正常編譯，xwrt和官方源碼的一直在下載軟件，編譯的軟件一樣的。
