### ISSUE TITLE
插件源一直报错

### ISSUE THREAD

**Issue by 805828526** [281677160/build-actions#88]
Run cd openwrt
正在执行：增加插件源,请耐心等待...
Error: Process completed with exit code [1]

lede的

**Comment by 281677160** [comment]
应该修复了，还发现有啥问题的再说说

**Comment by 805828526** [comment]
> 应该修复了，还发现有啥问题的再说说

还有个问题diy-part.sh的Password_free_login这个，设置1之后，进openwrt设置完密码，之后再次有需求进行更新后密码会被清空，设置0，密码会被重置为固件自带的密码而不是自己设置的密码，之前的老版本就没这个问题

**Comment by 281677160** [comment]
> > 应该修复了，还发现有啥问题的再说说
> 
> 还有个问题diy-part.sh的Password_free_login这个，设置1之后，进openwrt设置完密码，之后再次有需求进行更新后密码会被清空，设置0，密码会被重置为固件自带的密码而不是自己设置的密码，之前的老版本就没这个问题

设置0肯定是源码自带的密码啊，有问题？设置1就清空源码自带的密码，你说进固件后自己重新设置密码后会给清空？这个我没遇见过

**Comment by 805828526** [comment]
> > > 应该修复了，还发现有啥问题的再说说
> > 
> > 
> > 还有个问题 diy-part.sh 的Password_free_login这个，设置1之后，进openwrt设置完密码，之后再次有需求进行更新后密码会被清空，设置0，密码会被重置为固件自带的密码而不是自己设置的密码，之前的老版本就没这个问题
> 
> 设置0肯定是源码自带的密码啊，有问题？设置1就清空源码自带的密码，你说进固件后自己重新设置密码后会给清空？这个我没遇见过

事情是这样的，我首次编译是0，进去之后设置完密码，之后更新后发现密码清空了。

> > > 应该修复了，还发现有啥问题的再说说
> > 
> > 
> > 还有个问题diy-part.sh的Password_free_login这个，设置1之后，进openwrt设置完密码，之后再次有需求进行更新后密码会被清空，设置0，密码会被重置为固件自带的密码而不是自己设置的密码，之前的老版本就没这个问题
> 
> 设置0肯定是源码自带的密码啊，有问题？设置1就清空源码自带的密码，你说进固件后自己重新设置密码后会给清空？这个我没遇见过

事情是这样的，我首次编译是0，进去之后设置完密码，之后更新后发现密码清空了。于是我第二次编译的时候我把数值改为了1，密码被强制覆盖成了passwall，用的是lead的编译

**Comment by 805828526** [comment]
> > > 应该修复了，还发现有啥问题的再说说
> > 
> > 
> > 还有个问题diy-part.sh的Password_free_login这个，设置1之后，进openwrt设置完密码，之后再次有需求进行更新后密码会被清空，设置0，密码会被重置为固件自带的密码而不是自己设置的密码，之前的老版本就没这个问题
> 
> 设置0肯定是源码自带的密码啊，有问题？设置1就清空源码自带的密码，你说进固件后自己重新设置密码后会给清空？这个我没遇见过



> > > 应该修复了，还发现有啥问题的再说说
> > 
> > 
> > 还有个问题diy-part.sh的Password_free_login这个，设置1之后，进openwrt设置完密码，之后再次有需求进行更新后密码会被清空，设置0，密码会被重置为固件自带的密码而不是自己设置的密码，之前的老版本就没这个问题
> 
> 设置0肯定是源码自带的密码啊，有问题？设置1就清空源码自带的密码，你说进固件后自己重新设置密码后会给清空？这个我没遇见过



> > > 应该修复了，还发现有啥问题的再说说
> > 
> > 
> > 还有个问题diy-part.sh的Password_free_login这个，设置1之后，进openwrt设置完密码，之后再次有需求进行更新后密码会被清空，设置0，密码会被重置为固件自带的密码而不是自己设置的密码，之前的老版本就没这个问题
> 
> 设置0肯定是源码自带的密码啊，有问题？设置1就清空源码自带的密码，你说进固件后自己重新设置密码后会给清空？这个我没遇见过

事情是这样的，我首次编译是0，进去之后设置完密码，之后更新后发现密码清空了。于是我第二次编译的时候我把数值改为了1，密码被强制覆盖成了passwall，用的是Lede的编译

**Comment by 805828526** [comment]
事情是这样的，我首次编译是0，进去之后设置完密码，之后更新后发现密码清空了。于是我第二次编译的时候我把数值改为了1，密码被强制覆盖成了passwall，用的是lead的编译

> > > 应该修复了，还发现有啥问题的再说说
> > 
> > 
> > 还有个问题diy-part.sh的Password_free_login这个，设置1之后，进openwrt设置完密码，之后再次有需求进行更新后密码会被清空，设置0，密码会被重置为固件自带的密码而不是自己设置的密码，之前的老版本就没这个问题
> 
> 设置0肯定是源码自带的密码啊，有问题？设置1就清空源码自带的密码，你说进固件后自己重新设置密码后会给清空？这个我没遇见过

事情是这样的，我首次编译是0，进去之后设置完密码，之后更新后发现密码清空了。于是我第二次编译的时候我把数值改为了1，密码被强制覆盖成了passwall，用的是Lede的编译

**Comment by 281677160** [comment]
> 事情是这样的，我首次编译是0，进去之后设置完密码，之后更新后发现密码清空了。于是我第二次编译的时候我把数值改为了1，密码被强制覆盖成了passwall，用的是lead的编译
> 
> > > > 应该修复了，还发现有啥问题的再说说
> > > 
> > > 
> > > 还有个问题diy-part.sh的Password_free_login这个，设置1之后，进openwrt设置完密码，之后再次有需求进行更新后密码会被清空，设置0，密码会被重置为固件自带的密码而不是自己设置的密码，之前的老版本就没这个问题
> > 
> > 
> > 设置0肯定是源码自带的密码啊，有问题？设置1就清空源码自带的密码，你说进固件后自己重新设置密码后会给清空？这个我没遇见过
> 
> 事情是这样的，我首次编译是0，进去之后设置完密码，之后更新后发现密码清空了。于是我第二次编译的时候我把数值改为了1，密码被强制覆盖成了passwall，用的是Lede的编译

你的问题，我暂时理解不了，没办法搞，填0的话，源码本身自带密码的就自带密码，不自带密码的就不自带密码，填1的话，源码自带密码就会清空成不自带密码的，这个是源码，不是固件，编译好固件后，如果你设置的是1，那么首次登录openwrt是不需要密码就可以进入，然后修改你要的密码，修改完毕后，下次更新固件，如果是保留配置更新，就会还是保留你修改的密码，如果是不保留配置更新，就要看你编译之前设置的是0还是1的问题，我没发现进入之后修改了密码会给清空的，每次安装固件完毕，都会在30~40秒后重启一次openwrt，如果你是在这段时间内修改密码，那就是你没保存就发生重启了，那你的修改是不会成功的，安装完毕固件，在重启之前的30~40秒进入后台，基本上修改什么都难成功，除非你速度快，在重启之前密码保存你的修改

**Comment by 805828526** [comment]
> > 事情是这样的，我首次编译是0，进去之后设置完密码，之后更新后发现密码清空了。于是我第二次编译的时候我把数值改为了1，密码被强制覆盖成了passwall，用的是lead的编译
> > > > > 应该修复了，还发现有啥问题的再说说
> > > > 
> > > > 
> > > > 还有个问题diy-part.sh的Password_free_login这个，设置1之后，进openwrt设置完密码，之后再次有需求进行更新后密码会被清空，设置0，密码会被重置为固件自带的密码而不是自己设置的密码，之前的老版本就没这个问题
> > > 
> > > 
> > > 设置0肯定是源码自带的密码啊，有问题？设置1就清空源码自带的密码，你说进固件后自己重新设置密码后会给清空？这个我没遇见过
> > 
> > 
> > 事情是这样的，我首次编译是0，进去之后设置完密码，之后更新后发现密码清空了。于是我第二次编译的时候我把数值改为了1，密码被强制覆盖成了passwall，用的是Lede的编译
> 
> 你的问题，我暂时理解不了，没办法搞，填0的话，源码本身自带密码的就自带密码，不自带密码的就不自带密码，填1的话，源码自带密码就会清空成不自带密码的，这个是源码，不是固件，编译好固件后，如果你设置的是1，那么首次登录openwrt是不需要密码就可以进入，然后修改你要的密码，修改完毕后，下次更新固件，如果是保留配置更新，就会还是保留你修改的密码，如果是不保留配置更新，就要看你编译之前设置的是0还是1的问题，我没发现进入之后修改了密码会给清空的，每次安装固件完毕，都会在30-40秒后重启一次openwrt，如果你是在这段时间内修改密码，那就是你没保存就发生重启了，那你的修改是不会成功的，安装完毕固件，在重启之前的30-40秒进入后台，基本上修改什么都难成功，除非你速度快，在重启之前保存你的修改

好像在线更新才会这样，直接下载文件保留配置文件更新不会这样
