### ISSUE TITLE
Warning！

### ISSUE THREAD

**Issue by wuabuhuan** [281677160/build-actions#93]
正在执行：判断插件有否冲突减少编译错误
tmp/.config-package.in:66642:warning: config symbol defined without type
tmp/.config-package.in:66642:warning: config symbol defined without type

这是源码的错误还是本身脚本的错误？

**Comment by 281677160** [comment]
tmp/.config-package 这个错误都可以忽略，是额外增加插件时，某插件重复或者冲突所致，没多大关系
